name: Upload Changed Resources
on:
  push:
    branches:
      - master
      - main
    paths:
      - 'aws/main/custom-resources*'
      - 'aws/lambda/custom-resource/**'
  workflow_dispatch:

jobs:
  UploadChangedResources:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::060868188835:role/infra-github-runner

      - name: Check permissions
        run: |
          ls -la ./aws/main
          ls -la ./aws/scripts

      - name: Upload Changes
        run: bash ./aws/main/custom-resources

      # - name: Get Changed Files
      #   id: files
      #   uses: jitterbit/get-changed-files@v1

      # - name: Update Global Resources
      #   run: ./aws/scripts/update-global-resources
      
      # - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - run: echo "ğŸ This job's status is ${{ job.status }}."